#!/bin/sh

echo "Running cppcheck on FastJM..."

cppcheck --enable=all --inconclusive --quiet ./ > cppcheck_output.txt

if [ $? -ne 0 ]; then
    echo "Cppcheck found issues! Please review cppcheck_output.txt."
    exit 1
else
    echo "Cppcheck passed. Proceeding with commit."
fi
